site_name: Bash Style Guide
site_url: https://bsg.hthompson.dev
site_author: Hunter T.
site_description: A style guide for writing clean, consistent, and idiomatic Bash scripts.

repo_name: Bash Style Guide
repo_url: https://github.com/StrangeRanger/bash-style-guide

theme:
  name: material
  custom_dir: overrides
  palette:
    ## Palette toggle for dark mode.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue
      accent: blue
    ## Palette toggle for light mode.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: blue
  features:
    # When enabled, all content tabs across the whole documentation site will be linked
    # and switch to the same label when the user clicks on a tab.
    - content.tabs.link
    # Code blocks can automatically render a button on the right side to allow the user
    # to copy a code block's contents to the clipboard.
    - content.code.copy
    # When instant loading is enabled, clicks on all internal links will be intercepted
    # and dispatched via XHR without fully reloading the page.
    - navigation.instant
    # When anchor tracking is enabled, the URL in the address bar is automatically
    # updated with the active anchor as highlighted in the table of contents.
    - navigation.tracking
    # When sections are enabled, top-level sections are rendered as groups in the
    # sidebar for viewports above 1220px, but remain as-is on mobile.
    - navigation.sections
    # A back-to-top button can be shown when the user, after scrolling down, starts to
    # scroll up again. It's rendered centered and just below the header.
    - navigation.top
    # When search suggestions are enabled, the search will display the likeliest
    # completion for the last word which can be accepted with the Right key.
    - search.suggest
    # When search highlighting is enabled and a user clicks on a search result, Material
    # for MkDocs will highlight all occurrences after following the link.
    - search.highlight
    # When search sharing is activated, a share button is rendered next to the reset
    # button, which allows to deep link to the current search query and result.
    - search.share
  icon:
    annotation: material/plus-circle
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: matomo

extra_css:
  - stylesheets/extra.css

plugins:
  ## Built-in plugins.
  - search
  ## External plugins.
  # MkDocs plugin that enables displaying the date of the last git modification of a
  # page.
  - git-revision-date-localized:
      type: date
      timezone: America/Los_Angeles
      fallback_to_build_date: true
      enabled: true
  # TODO: Provide description of the below plugin.
  - exclude:
      glob:
        - "guidelines/common-mistakes.md"

markdown_extensions:
  # TODO: Provide description of the below extensions.
  - attr_list  # Required for Material for MkDocs Annotations to work.
  # The BetterEm extension improves the detection of Markup to emphasize text in
  # Markdown using special characters, i.e. for **bold** and _italic_ formatting.
  - pymdownx.betterem:
      smart_enable: all
  # The Admonition extension adds support for admonitions, more commonly known as
  # call-outs, which can be defined in Markdown by using a simple syntax.
  - pymdownx.blocks.admonition
  # The Details extension supercharges the Admonition extension, making the resulting
  # call-outs collapsible, allowing them to be opened and closed by the user.
  - pymdownx.blocks.details
  # The Tabbed extension allows the usage of content tabs, a simple way to group related
  # content and code blocks under accessible tabs.
  - pymdownx.blocks.tab:
      alternate_style: true
  # The Highlight extension adds support for syntax highlighting of code blocks (with
  # the help of SuperFences) and inline code blocks (with the help of InlineHilite).
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      #linenums: true
  # The InlineHilite extension add support for syntax highlighting of inline code
  # blocks. It's built on top of the Highlight extension, from which it sources its
  # configuration.
  - pymdownx.inlinehilite
  # The Keys extension adds a simple syntax to allow for the rendering of keyboard keys
  # and combinations.
  - pymdownx.keys
  # The SmartSymbols extension converts some sequences of characters into their
  # corresponding symbols, e.h. copyright symbols or fractions.
  - pymdownx.smartsymbols
  # The Snippets extension adds the ability to embed content from arbitrary files into a
  # document, including other documents or source files, by using a simple syntax.
  - pymdownx.snippets
  # The SuperFences extension allows for arbitrary nesting of code and content blocks
  # inside each other, including admonitions, tabs, lists and all other elements.
  - pymdownx.superfences

nav:
  - Home: index.md
  - Guidelines:
    - Aesthetics: guidelines/aesthetics.md
    - Bashism: guidelines/bashism.md
    - Style: guidelines/style.md
    - Error Handling: guidelines/error-handling.md
    # - Common Mistakes: guidelines/common-mistakes.md
  - Other:
    - TODO: other/todo.md
    - Changelog: other/changelog.md
    - License: other/license.md
